# -*- coding: utf-8 -*-
"""ЛАБА1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfeuvLljMO4GBkA31Qfe6sQ8w__r8ij-
"""

a=5
b=int(input("Введите значение для b: "))
print("Произведение a и b:",a*b)

a=int(input("Введите значение для a: "))
b=int(input("Введите значение для b: "))
print("Их сумма возведенная в квадрат",(a+b)**2)

a=15
b=10
c=int(input("Введите значение для c: "))
d=(a+b)/c
print(round(d,2))

a=int(input("Введите значение для a: "))
b=int(input("Введите значение для b: "))
c=(a**2)+(2*a*b)+(b**2)
print("квадрат суммы чисел",c)

a,b,c=map(int,input("Введите стороны треугольника ").split(","))
if a+b>c and a+c>b and b+c>a:
  p=a+b+c
  polp=p/2
  S=(polp* (polp - a) * (polp - b) * (polp - c)) ** 0.5
  print("Периметр",p)
  print("Площадь",round(S,2))
else: print("Такого треугольника не существует")

a=int(input("Введите значение для a: "))
b=int(input("Введите значение для b: "))
print(((a**3+14)/5)*b)

a=int(input())
n=int(input())
c=(a**2)//n
print(c)

n=int(input("Введите колво секунд "))
days=n//86400
ostsec=n%86400
hours=ostsec//3600
ostsec=ostsec%3600
minutes=ostsec//60
sec=ostsec%60
print(days,"Дней",hours,"Часов",minutes,"Минута",sec,"Секунд")

n = input("Введите целое число n: ")
odin = int(n)
dve = int(n * 2)
tri = int(n * 3)
schet=odin+dve+tri
print("Результат n + nn + nnn:",schet)