# -*- coding: utf-8 -*-
"""ЛАБА3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbxVnaUzPurNBo5DNFM_T6qr34Ia6iC2
"""

n=int(input())
if n<=12:
  if n==1:print('Январь');
  if n==2: print('Февраль');
  if n==3: print('март');
  if n==4: print('апрель');
  if n==5: print('май');
  if n==6: print('июнь');
  if n==7: print('июль');
  if n==8: print('август');
  if n==9: print('сентябрь');
  if n==10: print('октябрь');
  if n==11: print('ноябрь');
  if n==12: print('декабрь');
else: print('ты плохой')

a=int(input())
if a%2==0:print('ЧЕТНОЕ')
else:print('НЕЧЕТНОЕ')

n = int(input())
if n > 40:
  print("stonks")
else:
  print("not stonks")

def is_year_leap(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)
year = int(input("Введите год: "))
print(is_year_leap(year))

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True
n = int(input("Введите число: "))
print(is_prime(n))

def swap(a,b):
    c1=a > b * 3.6
    d=abs((-138/2)**1.3)
    d1=abs((-69/(28**5.1))*4)
    c2=d<=b<=d1
    if c1 or c2:
        a, b = b, a
    return a, b
a = float(input("Введите значение для a: "))
b = float(input("Введите значение для b: "))
a, b = swap(a,b)
print("Значение a:",a,"Значение b:",b)

skip 7

def schet(a,b,c):
  if c == -3:
     return "Ошибка: деление на ноль"
  res=round(((a**2+b**3)/(c+ 3))/4,2)
  chetne = "чётное" if int(res)%2==0 else "нечётное"
  return f"Результат:{res} Чётность:{chetne}"
a,b,c=map(float,input("Введите три числа для вычисления уравнения ").split(" "))
print(schet(a,b,c))